apiVersion: v1
kind: Service
metadata:
  name: fibonaccispiral-service
  namespace: fibonaccispiral
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: fibonaccispiral
    tier: ui
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fibonaccispiral
  namespace: fibonaccispiral
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fibonaccispiral
      tier: ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fibonaccispiral
        tier: ui
    spec:
      containers:
      - name: fibonaccispiral
